=== AbdulazizNafea/SQLServerIntegrationServices-SSIS/134/XmlReviewTool 2.3/ReviewToolSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ReviewTool">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Chapter" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Questions" maxOccurs="1" minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Question" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Answers">
														<xs:complexType>
															<xs:sequence>
																<xs:element maxOccurs="unbounded" name="Answer">
																	<xs:complexType>
																		<xs:attribute name="letter" type="xs:string" use="required" />
																		<xs:attribute name="textAnswer" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="correctAnswer" type="xs:string" use="required" />
												<xs:attribute name="questionNumber" type="xs:unsignedByte" use="required" />
												<xs:attribute name="questionText" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="number" type="xs:unsignedByte" use="required" />
						<xs:attribute name="title" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="courseNumber" type="xs:unsignedShort" use="required" />
			<xs:attribute name="courseTitle" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AbdulazizNafea/SQLServerIntegrationServices-SSIS/134/XmlReviewTool 2.3/134Review.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ReviewTool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ReviewToolSchema.xsd"
 courseNumber="134" courseTitle="SQL Server Integration Services: Migrating Data for Business Intelligence">
<Chapter number="1" title="Getting Started with SQL Server Integration Services (SSIS)">
  <Questions>
    <Question correctAnswer="D" questionNumber="1" questionText="Which of the following is an executable inside a package?">
      <Answers>
        <Answer letter="A" textAnswer="Task" />
        <Answer letter="B" textAnswer="Container" />
        <Answer letter="C" textAnswer="Event handler" />
        <Answer letter="D" textAnswer="All the above" />
      </Answers>
    </Question>
    <Question correctAnswer="C" questionNumber="2" questionText="Tasks are configured on which tab of SSIS Designer?">
      <Answers>
        <Answer letter="A" textAnswer="Data Flow tab" />
        <Answer letter="B" textAnswer="Progress tab" />
        <Answer letter="C" textAnswer="Control Flow tab" />
        <Answer letter="D" textAnswer="Package Explorer tab" />
      </Answers>
    </Question>
    <Question correctAnswer="A" questionNumber="3" questionText="Transformations are configured on which tab of SSIS Designer?">
      <Answers>
        <Answer letter="A" textAnswer="Data Flow tab" />
        <Answer letter="B" textAnswer="Progress tab" />
        <Answer letter="C" textAnswer="Control Flow tab" />
        <Answer letter="D" textAnswer="Package Explorer tab" />
      </Answers>
    </Question>
    <Question correctAnswer="B" questionNumber="4" questionText="A task is a">
      <Answers>
        <Answer letter="A" textAnswer="Data flow element" />
        <Answer letter="B" textAnswer="Control Flow element" />
        <Answer letter="C" textAnswer="Transformation" />
        <Answer letter="D" textAnswer="All the above" />
      </Answers>
    </Question>
      <Question correctAnswer="D" questionNumber="5" questionText="A transformation is a">
      <Answers>
        <Answer letter="A" textAnswer="Container" />
        <Answer letter="B" textAnswer="Control Flow element" />
        <Answer letter="C" textAnswer="Task" />
        <Answer letter="D" textAnswer="Data Flow element" />
      </Answers>
    </Question>

    <Question correctAnswer="D" questionNumber="6" questionText="Which tool would you use to author an Integration Services package?">
      <Answers>
        <Answer letter="A" textAnswer="SQL Server Management Studio" />
        <Answer letter="B" textAnswer="SQL Server Enterprise Manager" />
        <Answer letter="C" textAnswer="SQL Server Configuration Tool" />
        <Answer letter="D" textAnswer="SQL Server Data Tools" />
      </Answers>
    </Question>
    <Question correctAnswer="B" questionNumber="7" questionText="What must be configured in order to send mail from an SSIS package task?">
      <Answers>
        <Answer letter="A" textAnswer="An Outlook profile" />
        <Answer letter="B" textAnswer="SMTP connection manager" />
        <Answer letter="C" textAnswer="A mail box account for SSIS" />
        <Answer letter="D" textAnswer="DNS reverse lookup" />
      </Answers>
    </Question>
  </Questions>
</Chapter>
<Chapter number="2" title="Simple Data Migration and Scripting">
  <Questions>
    <Question correctAnswer="C" questionNumber="1" questionText="Which of the following is not a precedent contraint condition?">
      <Answers>
        <Answer letter="A" textAnswer="On Success" />
        <Answer letter="B" textAnswer="On Failure" />
        <Answer letter="C" textAnswer="On Event" />
        <Answer letter="D" textAnswer="On Completion" />
      </Answers>
    </Question>
    <Question correctAnswer="B" questionNumber="2" questionText="A connection manager is resolved to an actual connection at">
      <Answers>
        <Answer letter="A" textAnswer="Design time" />
        <Answer letter="B" textAnswer="Runtime" />
        <Answer letter="C" textAnswer="Compile time" />
        <Answer letter="D" textAnswer="Termination" />
      </Answers>
    </Question>
    <Question correctAnswer="A" questionNumber="3" questionText="What type of connection manager would you configure when connecting to a data source with an installed OLE DB provider?">
      <Answers>
        <Answer letter="A" textAnswer="OLE DB Connection Manager" />
        <Answer letter="B" textAnswer="SQL Server Connection Manager" />
        <Answer letter="C" textAnswer="Flat File Connection Manager" />
        <Answer letter="D" textAnswer="Analysis Services Connection Manager" />
      </Answers>
    </Question>
    <Question correctAnswer="D" questionNumber="4" questionText="What type of connection manager would you configure in order to collect system information on a remote computer?">
      <Answers>
        <Answer letter="A" textAnswer="OLE DB Connection Manager" />
        <Answer letter="B" textAnswer="SQL Server Connection Manager" />
        <Answer letter="C" textAnswer="Registry Connection Manager" />
        <Answer letter="D" textAnswer="WMI Connection Manager" />
      </Answers>
    </Question>
    <Question correctAnswer="B" questionNumber="5" questionText="When importing data into a SQL Server table, the most important difference between the Bulk Insert and Data Flow tasks is:">
      <Answers>
        <Answer letter="A" textAnswer="The Data Flow task does not perform any transformations on data." />
        <Answer letter="B" textAnswer="The Bulk Insert task does not perform any transformations on data." />
        <Answer letter="C" textAnswer="The Bulk Insert task can source data from any OLE DB or ADO.NET data source." />
        <Answer letter="D" textAnswer="The Data Flow task is always invariably much faster than the Bulk Insert task." />
      </Answers>
    </Question>
    <Question correctAnswer="C" questionNumber="6" questionText="Multiple tasks in a package can execute">
      <Answers>
        <Answer letter="A" textAnswer="Only serially" />
        <Answer letter="B" textAnswer="Only in parallel" />
        <Answer letter="C" textAnswer="Both serially and in parallel, depending on precedence constraints" />
        <Answer letter="D" textAnswer="Always simultaneously" />
      </Answers>
    </Question>
    <Question correctAnswer="C" questionNumber="7" questionText="The Execute SQL task does not return the following result set type:">
      <Answers>
        <Answer letter="A" textAnswer="Single row" />
        <Answer letter="B" textAnswer="Full result set (multiple rows)" />
        <Answer letter="C" textAnswer="Comma delimited text" />
        <Answer letter="D" textAnswer="XML" />
      </Answers>
    </Question>
    <Question correctAnswer="C" questionNumber="8" questionText="What should be configured in order to view data transformed by one component before it is processed by the next component in a data flow?">
      <Answers>
        <Answer letter="A" textAnswer="Package Deployment Model" />
        <Answer letter="B" textAnswer="An SMTP connection manager" />
        <Answer letter="C" textAnswer="Enable Data viewer" />
        <Answer letter="D" textAnswer="Run64BitRuntime flag" />
      </Answers>
    </Question>
    <Question correctAnswer="A" questionNumber="9" questionText="Which of the following is not a legitimate scope for a variable?">
      <Answers>
        <Answer letter="A" textAnswer="constraint" />
        <Answer letter="B" textAnswer="package" />
        <Answer letter="C" textAnswer="container" />
        <Answer letter="D" textAnswer="task" />
      </Answers>
    </Question>
    <Question correctAnswer="D" questionNumber="10" questionText="The two default variable namespaces are:">
      <Answers>
        <Answer letter="A" textAnswer="System and Package" />
        <Answer letter="B" textAnswer="User and Package" />
        <Answer letter="C" textAnswer="System and Task" />
        <Answer letter="D" textAnswer="System and User" />
      </Answers>
    </Question>
    <Question correctAnswer="B" questionNumber="11" questionText="To pass information between tasks, use the following:">
      <Answers>
        <Answer letter="A" textAnswer="Precedent constraint" />
        <Answer letter="B" textAnswer="User variable" />
        <Answer letter="C" textAnswer="Namespace" />
        <Answer letter="D" textAnswer="Property bag" />
      </Answers>
    </Question>
    <Question correctAnswer="D" questionNumber="12" questionText="The Script task can be programmed using:">
      <Answers>
        <Answer letter="A" textAnswer="C#" />
        <Answer letter="B" textAnswer="VB.Net" />
        <Answer letter="C" textAnswer="Any .NET language" />
        <Answer letter="D" textAnswer="A or B" />
      </Answers>
    </Question>
    <Question correctAnswer="D" questionNumber="13" questionText="Which of the following fragments of code within a Script task would change the contents of a variable called FullName?">
      <Answers>
        <Answer letter="A" textAnswer="SSIS.Variables[&quot;FullName&quot;].Value = &quot;John Doe&quot;;" />
        <Answer letter="B" textAnswer="@FullName = &quot;John Doe&quot;;" />
        <Answer letter="C" textAnswer="@[User:FullName] = &quot;John Doe&quot;;" />
        <Answer letter="D" textAnswer="Dts.Variables[&quot;FullName&quot;].Value = &quot;John Doe&quot;;" />
      </Answers>
    </Question>

  </Questions>
</Chapter>
<Chapter number="3" title="Common SSIS Tasks">
  <Questions>
    <Question correctAnswer="C" questionNumber="1" questionText="Which of the following package configurations can store multiple values?">
      <Answers>
        <Answer letter="A" textAnswer="XML file" />
        <Answer letter="B" textAnswer="SQL Server table" />
        <Answer letter="C" textAnswer="Both of the above" />
        <Answer letter="D" textAnswer="Environment variable" />
      </Answers>
    </Question>
